### ISSUE TITLE
error/warning: left shift of negative value

### ISSUE THREAD

**Issue by olk** [boostorg/dynamic_bitset#19]
compiling unit-tests with gcc -W -Wall -Werror produces errors like:

../../../boost/dynamic_bitset/dynamic_bitset.hpp:1953:57: error: left shift of negative value [-Werror=shift-negative-value]
block_type const mask = (~static_cast(0) << extra_bits);

**Comment by mclow** [comment]
Since I complained about your proposed fix, I'll take a look at this.

**Comment by mclow** [comment]
I'm not getting these warnings with clang.  I'll try with gcc.

**Comment by olk** [comment]
b2 toolset=gcc cxxflags="-std=c++17 -W -Wall -Werror" -j 32

dyn_bitset_unit_tests2.cpp:285:33:   von hier erfordert
../../../boost/dynamic_bitset/dynamic_bitset.hpp:1953:57: Fehler: left shift of negative value [-Werror=shift-negative-value]
         block_type const mask = (~static_cast<Block>(0) << extra_bits);


gcc -v: gcc-Version 7.2.1

**Comment by mclow** [comment]
Must be a new warning with 7.2; I don't get them with 7.1.
/me Off to install a newer version....

**Comment by olk** [comment]
got this with gcc-6.3.0 too

**Comment by mclow** [comment]
Ok - `c++17` is the key.

**Comment by olk** [comment]
b2 toolset=gcc cxxflags="-std=c++11 -W -Wall -Werror" -j 32 prduces the same error (Arch Linux, gcc-7.2.1)

**Comment by mclow** [comment]
Fixed in d3eb4faf0cc0d7a7f0492fc60f490c95066282bf

**Comment by olk** [comment]
fix works, thx

**Comment by igorsugak** [comment]
I just discovered this same bug with UBSAN:
`dynamic_bitset.hpp:1943:55: runtime error: left shift of negative value -1`
Thank you for fixing this!
